### PR TITLE
Project rename

### LINKED ISSUE #1: Rename project files to Railway Relays Tester
Before starting the development, it would be nice if the references to DIMBA project like files, directories and projects could be renamed using the name of this project.

### PR DESCRIPTION
**Pull request by cmancon**
Resolves #1 

Waiting the comments of @leanfrancucci to add some more changes.

### CODE REVIEW

**Comment by leanfrancucci** [comment]
Please, don't forget to recompile both [CIAA](https://github.com/gicsafe-firmware/rrtester/tree/develop/dimba/arch/ciaa-nxp_freertos/build) and [PC](https://github.com/gicsafe-firmware/rrtester/tree/develop/dimba/arch/win/build) projects

**Comment by leanfrancucci** [comment]
What do you think about to change the name of [this](https://github.com/gicsafe-firmware/rrtester/tree/develop/dimba) directory for `src`?

**Comment by cmancon** [comment]
[](url)

> Please, don't forget to recompile both [CIAA](https://github.com/gicsafe-firmware/rrtester/tree/develop/dimba/arch/ciaa-nxp_freertos/build) and [PC](https://github.com/gicsafe-firmware/rrtester/tree/develop/dimba/arch/win/build) projects

Working on it

**Comment by cmancon** [comment]
> What do you think about to change the name of [this](https://github.com/gicsafe-firmware/rrtester/tree/develop/dimba) directory for `src`?

I agree. I'll do it unless someone has a reason against it.

**Comment by cmancon** [comment]
What about the test files? How must we to integrate them to the project?

**Comment by leanfrancucci** [comment]
Yes

**Comment by leanfrancucci** [comment]
The modules under ceedling framework, which were fixed by you and Bruno, are ceedling projects. I don't understand very well your question.

**Comment by cmancon** [comment]
I bumped with some errors while compiling in the MCUxpresso that I haven't thought of. When building the production code, the IDE tries to compile the test files too and returns errors with at least the mock_ inclusions.
How should the IDE 'project' deal with the tests? Are going to launch the test suite with the IDE? If not, does it worth it to have them in the IDE 'project'?

**Review by dariosb — CHANGES_REQUESTED** [review]
No estoy del todo de acuerdo con el cambio de algunos nombres de fuentes y funciones. 
En algunos, por ejemplo las definiciones de configuración, les buscaría un nombre mas genérico. Por ejemplo:
el módulo conmgr.c, o el futuro ethMgr.c, se van a reutilizar tanto para DIMBA como para RRTESTER por lo tanto el include xxxCfg que en cada caso es dimbaCfg.h o rrtesterCfg.h le pondría un nombre mas genérico para no tener que editar conmgr.c y ethMgr con cada proyecto. Se me ocurre por ejemplo config.h y a secas.
Ademas las funciones de xxxCfg_clientId y xxxCfg_topic las quitaría de main.c y llevaría a un módulo config.c
A el módulo publisher.c y su .h les pondría un nombre específico de la app tal como tienen las funciones que implementa.
Los cambios en el modulo bsp.c para x86 los veo ok

**Comment by dariosb** [comment]
Test files should be out of production compilation. You don't have to include the entire folder module to the eclipse project. You must create a virtual folder and then link source files. Take the original project as a refference.

**Review by dariosb — APPROVED** [review]
Still pending for config an publisher module rename

**Pull request merged**
